application: jmoritphp
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: index.php
  
- url: /index\.php
  script: index.php

- url: /errormessage\.php
  script: errormessage.php
  
- url: /bustrip\.php
  script: bustrip.php
  
- url: /christmastree\.php
  script: christmastree.php
  
- url: /swimclubs\.php
  script: swimclubs.php
  
- url: /barberagenda\.php
  script: barberagenda.php
  
- url: /functions\.php
  script: functions.php
  
- url: /login\.php
  script: login.php
  
- url: /logout\.php
  script: logout.php
  
- url: /userpage\.php
  script: userpage.php
  
- url: /adminpage\.php
  script: adminpage.php  


